source 'https://github.com/CocoaPods/Specs'
platform :ios, '9.0'
use_frameworks!
# Add Application pods here
def app_pods
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.0'
    pod 'Crashlytics', '~> 3.8'
    pod 'Decodable', '~> 0.5'
    pod 'DeepLinkKit', '~> 1.2.1'
    pod 'DynamicColor', '~> 3.1'
    pod 'Ecno', '~> 1.0.0'
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'
    pod 'Fabric', '~> 1.6'
    pod 'Firebase', '~> 3.6.0'
    pod 'Firebase/DynamicLinks'
    pod 'FXPageControl', '~> 1.4'
    pod 'KeychainAccess', '~> 3.0'
    pod 'NVActivityIndicatorView', '~> 3.0'
    pod 'Opera', :git => 'https://github.com/xmartlabs/Opera.git', :branch => 'Swift3'
    pod 'R.swift', '~> 3.0'
    pod 'RealmSwift', '~> 1.1'
    pod 'Result', '~> 3.0'
    pod 'RxCocoa', '~> 3.0.0-beta.1'
    pod 'RxSwift',  '~> 3.0.0-beta.1'
    pod 'RxRealm', '~> 0.2.3'
    pod 'SkyFloatingLabelTextField', '~> 1.2'
    pod 'SwiftDate', '~> 4.0'
    pod 'SwiftyJSON', '3.0.0'
    pod 'XLSwiftKit', '~> 2.0'
    pod 'OAuthSwift', '~> 1.0'
end
def testing_pods
    # pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
    # pod 'Nimble', '~> 4.0'
end
target 'Iujuu' do
    app_pods
end
target 'Iujuu-Staging' do
    app_pods
end
target 'Tests' do
  testing_pods
end
target 'UITests' do
    testing_pods
end
post_install do |installer|
    puts 'Removing static analyzer support'
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
