source 'https://github.com/CocoaPods/Specs'
platform :ios, '9.0'
use_frameworks!
# Add Application pods here
def app_pods
    pod 'Alamofire', '~> 4.0'
    pod 'AlamofireImage', '~> 3.0'
    # pod 'AsyncSwift', '~> 1.0'
    pod 'Crashlytics', '~> 3.8'
    # pod 'Device', '~> 1.0'
    pod 'Decodable', :git => 'https://github.com/Anviking/Decodable.git', :branch => 'master'
    pod 'DynamicColor', '~> 3.1'
    pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift3'
    pod 'Fabric', '~> 1.6'
    pod 'KeychainAccess', '~> 3.0'
    pod 'NVActivityIndicatorView', '~> 3.0'
    # pod 'Opera', :git => 'https://github.com/xmartlabs/Opera.git', :branch => 'master'
    pod 'R.swift', '~> 3.0'
    pod 'RealmSwift', '~> 1.1'
    pod 'Result', '~> 3.0'
    # pod 'RxAlamofire', '~> 2.2'
    pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '3.0.0-beta.1'
    pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :tag => '3.0.0-beta.1'
    pod 'SwiftDate', :git => 'https://github.com/malcommac/SwiftDate.git', :branch => 'feature/swift-3.0'
    # pod 'WebLinking', '~> 1.0'
    pod 'XLSwiftKit', '~> 2.0'
end
def testing_pods
    pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
    # pod 'Nimble', '~> 4.0'
end
target 'Iujuu' do
    app_pods
end
target 'Iujuu-Staging' do
    app_pods
end
target 'Tests' do
  testing_pods
end
target 'UITests' do
    testing_pods
end
post_install do |installer|
    puts 'Removing static analyzer support'
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
